include:
 - board: seeeduino_xiao_ble
   shield: KobitoKey_left rgbled_adapter
   snippet: studio-rpc-usb-uart
   
 - board: seeeduino_xiao_ble
   # ▼ rgbled_adapter を削除しました
   shield: KobitoKey_right

 - board: seeeduino_xiao_ble
   shield: settings_reset
