include:
 - board: seeeduino_xiao_ble
   shield: KobitoKey_left rgbled_adapter
   snippet: studio-rpc-usb-uart
   
 - board: seeeduino_xiao_ble
   # ▼ rgbled_adapter を復活させる（右側）
   shield: KobitoKey_right rgbled_adapter

 - board: seeeduino_xiao_ble
   shield: settings_reset
