manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hsgw
      url-base: https://github.com/hsgw
    - name: caksoylar
      url-base: https://github.com/caksoylar  
    - name: prospector
      url-base: https://github.com/t-ogura

  projects:
    # ZMK 本体
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    
    # Sensor-rotation
    - name: zmk-feature-sensor_rotation
      remote: hsgw
      revision: main

    # LED
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

    # Prospector Scanner モジュール
    - name: prospector-zmk-module
      remote: prospector
      revision: main
      
  self:
    path: config
